name: Forecast Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run forecast script
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        python forecast_pipeline.py

    - name: Commit updated forecast file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add forecast_temp_for_supaboard.csv
        git commit -m "Auto-update forecast CSV"
        git push
